name: random_please
description: Random Please - A comprehensive toolkit for everyday utilities
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  intl: 0.20.2 
  shared_preferences: 2.2.2
  crypto: ^3.0.3
  http: ^1.2.1
  math_expressions: ^2.6.0
  flutter_localizations:
    sdk: flutter  
  flutter_gen: 5.10.0  
  logger: 2.5.0
  logging: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  window_manager: ^0.5.0
  flutter_colorpicker: ^1.1.0
  # P2P Data Transfer dependencies
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  multicast_dns: ^0.3.2+6
  socket_io_client: ^2.0.3+1
  dio: ^5.4.3+1
  encrypt: ^5.0.3
  uuid: ^4.4.0
  nsd: ^4.0.3
  # workmanager: ^0.5.1  # Temporarily disabled due to Flutter compatibility issues
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path: ^1.8.3
  markdown_widget: ^2.3.2+8
  url_launcher: ^6.2.4
  package_info_plus: ^8.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  remove_unused_localizations: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/